import { NextResponse } from "next/server";
import { createClient } from "@/utils/supabase/server";
import type { PropertyType } from "@/types/database";

export async function POST(req: Request) {
  const supabase = createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  let body: {
    address_line1: string;
    address_line2: string | null;
    city: string;
    state: string;
    zip: string;
    property_type: PropertyType | null;
    price: number | null;
    bedrooms: number | null;
    bathrooms: number | null;
    sqft: number | null;
    lot_size: string | null;
    year_built: number | null;
    homeowner_name: string;
    homeowner_email: string | null;
    homeowner_phone: string | null;
    send_intake_now: boolean;
  };

  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid request body." }, { status: 400 });
  }

  // Basic server-side validation
  if (!body.address_line1?.trim() || !body.city?.trim() || !body.state || !body.zip?.trim()) {
    return NextResponse.json({ error: "Address fields are required." }, { status: 422 });
  }

  // Create the listing — intake_token is generated by the DB default
  const { data: listing, error } = await supabase
    .from("listings")
    .insert({
      realtor_id: user.id,
      address_line1: body.address_line1.trim(),
      address_line2: body.address_line2,
      city: body.city.trim(),
      state: body.state,
      zip: body.zip.trim(),
      property_type: body.property_type,
      price: body.price,
      bedrooms: body.bedrooms,
      bathrooms: body.bathrooms,
      sqft: body.sqft,
      lot_size: body.lot_size,
      year_built: body.year_built,
      status: body.send_intake_now ? "intake_pending" : "draft",
      intake_sent_at: body.send_intake_now ? new Date().toISOString() : null,
    })
    .select("id, intake_token")
    .single();

  if (error || !listing) {
    console.error("listings insert error:", error);
    return NextResponse.json({ error: "Failed to create listing." }, { status: 500 });
  }

  // If send_intake_now, email would be dispatched here via a transactional
  // email service (e.g. Resend). Wired in a later step — token is ready.
  // intake link: /intake/{listing.intake_token}

  return NextResponse.json({ id: listing.id }, { status: 201 });
}
