import Link from "next/link";

export const metadata = {
  title: "Disclaimer & Legal Notice | Limen",
  description: "Important disclaimers regarding AI-generated content, Fair Housing compliance, and agent responsibilities on the Limen platform.",
};

export default function DisclaimerPage() {
  const sections = [
    {
      title: "AI-Generated Content",
      content: `Limen uses artificial intelligence to generate real estate listing copy, social media content, and marketing materials based on information provided by real estate agents and homeowners. All content generated by Limen is produced automatically and has not been reviewed by a licensed attorney, broker, or compliance officer prior to delivery.

AI-generated content may contain errors, inaccuracies, or omissions. Real estate agents and brokers are solely responsible for reviewing all generated content for accuracy, completeness, and compliance with applicable laws and regulations before publishing, distributing, or submitting such content to any multiple listing service, real estate portal, social media platform, or any other channel.

Limen makes no warranties, express or implied, regarding the accuracy, fitness for a particular purpose, or legal compliance of any AI-generated content.`,
    },
    {
      title: "Fair Housing Compliance",
      content: `Limen incorporates Fair Housing compliance guidelines into its AI generation process and performs an automated review of generated content. However, this automated review does not constitute a legal compliance determination, a legal opinion, or a guarantee that any generated content complies with the Fair Housing Act, applicable state fair housing laws, or any other anti-discrimination statute.

Real estate agents, brokers, and their employing brokerages are solely responsible for ensuring that all listing descriptions, marketing copy, and communications comply with the Fair Housing Act (42 U.S.C. § 3604 et seq.), applicable state and local fair housing laws, and all rules and regulations of the applicable multiple listing service.

Limen's Fair Housing review is an automated tool intended to assist agents in identifying potentially problematic language. It is not a substitute for professional legal review. Limen is not liable for any Fair Housing violation, complaint, investigation, fine, or legal proceeding arising from content generated, modified, approved, or distributed through the Limen platform.`,
    },
    {
      title: "Agent and Broker Responsibility",
      content: `By using Limen, real estate agents and brokers acknowledge and agree that:

1. They are licensed real estate professionals subject to applicable state licensing laws and the rules and regulations of their employing broker and multiple listing service.

2. All content generated by Limen must be reviewed and approved by the agent or broker prior to use. The agent's or broker's decision to approve, publish, or distribute any Limen-generated content constitutes their acceptance of full responsibility for that content.

3. Limen is a marketing content generation tool and does not provide real estate advice, legal advice, financial advice, appraisal services, or brokerage services.

4. Agents are responsible for verifying that all property facts, specifications, and descriptions included in listing content are accurate and do not constitute misrepresentation under applicable real estate law.`,
    },
    {
      title: "Accuracy of Information",
      content: `Limen generates content based on information entered by the agent and homeowner. Limen does not independently verify property details, MLS data, tax records, square footage, room counts, renovation descriptions, or any other property information.

Agents are responsible for the accuracy of all information entered into the Limen platform. Limen is not liable for any claim, dispute, or legal proceeding arising from inaccurate property information used to generate listing content.`,
    },
    {
      title: "Intellectual Property",
      content: `Content generated by Limen using your property information and inputs is intended for your use in marketing your listings. Limen does not claim ownership of the final generated output specific to your listings.

By using Limen, you grant Limen a limited license to process your inputs to generate the requested content. You represent that you have the right to submit all information provided to Limen, including homeowner-provided details and listing photographs.`,
    },
    {
      title: "Photography and Visual Content",
      content: `Limen allows agents to upload listing photographs for use in AI vision analysis and social media preview generation. By uploading photographs to Limen, you represent that you own or have the right to use such photographs for the purpose of generating listing marketing content.

Limen is not responsible for copyright infringement arising from photographs uploaded by users. Agents are responsible for obtaining appropriate permissions for all photographs used on the platform.`,
    },
    {
      title: "Limitation of Liability",
      content: `To the maximum extent permitted by applicable law, Limen and its affiliates, officers, employees, and agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from or related to your use of the Limen platform, including but not limited to Fair Housing violations, MLS violations, client disputes, or regulatory actions.

Limen's total liability to any user for any claim arising from use of the platform shall not exceed the total subscription fees paid by that user in the twelve months preceding the claim.`,
    },
    {
      title: "Changes to This Disclaimer",
      content: `Limen reserves the right to update this disclaimer at any time. Continued use of the Limen platform following any update constitutes acceptance of the revised disclaimer. We encourage users to review this page periodically.`,
    },
  ];

  return (
    <div className="min-h-screen bg-parchment">
      <header className="bg-ink px-6 py-4 flex items-center justify-between">
        <Link href="/dashboard" className="text-gilt font-serif text-xl tracking-widest">LIMEN</Link>
        <Link href="/dashboard" className="text-parchment text-sm opacity-70 hover:opacity-100 font-sans">← Dashboard</Link>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-12">
        <div className="mb-10">
          <h1 className="font-serif text-4xl text-ink mb-3">Disclaimer & Legal Notice</h1>
          <p className="font-sans text-sm text-stone">Last updated: May 2026</p>
          <div className="mt-4 bg-amber-50 border border-amber-200 rounded-lg px-5 py-4">
            <p className="font-sans text-sm text-amber-800 leading-relaxed">
              <strong>Important:</strong> By using Limen, you acknowledge that you have read, understood, and agreed to the terms of this disclaimer. Real estate agents and brokers are solely responsible for reviewing all AI-generated content before use and for ensuring compliance with all applicable laws and regulations.
            </p>
          </div>
        </div>

        <div className="space-y-8">
          {sections.map((section, i) => (
            <div key={i} className="bg-white border border-stone/20 rounded-lg p-6 space-y-3">
              <h2 className="font-serif text-xl text-ink">{section.title}</h2>
              <div className="space-y-3">
                {section.content.split("\n\n").map((para, j) => (
                  <p key={j} className="font-sans text-sm text-stone leading-relaxed whitespace-pre-line">{para}</p>
                ))}
              </div>
            </div>
          ))}
        </div>

        <div className="mt-10 pt-8 border-t border-stone/20 text-center space-y-3">
          <p className="font-sans text-xs text-stone">
            Questions about these terms? Contact us at{" "}
            <a href="mailto:legal@limenai.org" className="text-gilt hover:underline">legal@limenai.org</a>
          </p>
          <div className="flex justify-center gap-6">
            <Link href="/privacy-policy" className="font-sans text-xs text-stone hover:text-ink">Privacy Policy</Link>
            <Link href="/sms-terms" className="font-sans text-xs text-stone hover:text-ink">SMS Terms</Link>
            <Link href="/dashboard" className="font-sans text-xs text-stone hover:text-ink">Back to Dashboard</Link>
          </div>
        </div>
      </main>
    </div>
  );
}
